executable              = run.sh
arguments               = $(dir)
Initialdir              = /afs/cern.ch/user/r/repan/work/top_pair/condor_semi/condor_out/$(dir)
						
output                  = run.out
error                   = run.err
log                     = run.log
						
RequestMemory           = 2000
ShouldTransferFiles     = NO
+JobFlavour             = "nextweek"
x509userproxy           = $ENV(HOME)/temp/x509up
Queue dir from ../condor_list.txt
